import type { ResourceMaster } from "@/lib/resources/types";

export const mockResources: ResourceMaster[] = [
  {
    id: "res_venue_klcc_mock",
    resourceType: "venue",
    resourceName: "Kuala Lumpur Convention Centre [MOCK]",
    supplierName: "KLCC Convention Centre Sdn Bhd [MOCK]",
    city: "吉隆坡",
    district: "KLCC",
    serviceScope: ["会议厅", "展览空间", "宴会支持"],
    suitableScenarios: ["经销商大会", "新品发布会", "大型论坛"],
    capacityOrSpec: "Plenary Hall 约 2,991 人，具体厅型需二次确认 [MOCK]",
    referencePriceMin: 80000,
    referencePriceMax: 180000,
    currency: "MYR",
    pricingUnit: "场地/天",
    priceScopeNote: "仅为公开资料与历史沟通形成的参考范围，不含餐饮、搭建、税费与服务费 [MOCK]",
    seasonalityRule: "展会旺季、周末和热门档期价格可能上浮 [MOCK]",
    dateConflictSensitivity: "high",
    minimumOrderRequirement: "大型厅型通常需结合餐饮或多日档期确认 [MOCK]",
    leadTimeRequirement: "建议提前 90-180 天询档 [MOCK]",
    requiresQuoteConfirmation: true,
    strategicCooperationLevel: "strategic",
    agreementStatus: "mock",
    customerVisibleSummary: "适合大型企业会议和发布活动，正式档期与价格需按本次活动询价确认 [MOCK]",
    internalNegotiationNote: "内部备注：优先询问淡季平日组合空间与餐饮打包空间 [MOCK]",
    internalRiskNote: "内部风险：热门档期冲突敏感，客户预算不足时需先缩小厅型 [MOCK]",
    contentStatus: "mock",
    lastVerifiedAt: "2026-07-04",
  },
  {
    id: "res_venue_banyan_kl_mock",
    resourceType: "venue",
    resourceName: "Banyan Tree Kuala Lumpur [MOCK]",
    supplierName: "Banyan Tree Kuala Lumpur [MOCK]",
    city: "吉隆坡",
    district: "Bukit Bintang / Conlay",
    serviceScope: ["小型会议", "高端私享活动", "住宿协同"],
    suitableScenarios: ["高管闭门会", "商务接待", "小型培训"],
    capacityOrSpec: "Meet & Feed Capacity 约 40 人，具体空间需确认 [MOCK]",
    referencePriceMin: 12000,
    referencePriceMax: 45000,
    currency: "MYR",
    pricingUnit: "空间与餐饮组合/场",
    priceScopeNote: "参考范围取决于包场时段、餐饮标准和住宿需求 [MOCK]",
    seasonalityRule: "节假日、房态紧张或高端宴请时段需重新核价 [MOCK]",
    dateConflictSensitivity: "medium",
    minimumOrderRequirement: "可能存在餐饮最低消费或住宿绑定条件 [MOCK]",
    leadTimeRequirement: "建议提前 30-60 天询档 [MOCK]",
    requiresQuoteConfirmation: true,
    strategicCooperationLevel: "preferred",
    agreementStatus: "mock",
    customerVisibleSummary: "适合小型高规格会务或贵宾接待，正式条件需顾问询价确认 [MOCK]",
    internalNegotiationNote: "内部备注：可优先争取住宿与会议空间联动报价 [MOCK]",
    internalRiskNote: "内部风险：不适合百人以上大会，避免客户误解容量 [MOCK]",
    contentStatus: "mock",
    lastVerifiedAt: "2026-07-04",
  },
  {
    id: "res_banquet_chinese_mock",
    resourceType: "banquet",
    resourceName: "中式商务晚宴供应商 [MOCK]",
    supplierName: "KL Chinese Banquet Partner [MOCK]",
    city: "吉隆坡",
    district: "市中心 / PJ",
    serviceScope: ["中式围餐", "清真友好菜单协调", "酒水服务"],
    suitableScenarios: ["经销商答谢宴", "客户招待", "颁奖晚宴"],
    capacityOrSpec: "80-300 人，按餐标与包间/宴会厅确认 [MOCK]",
    referencePriceMin: 180,
    referencePriceMax: 420,
    currency: "MYR",
    pricingUnit: "人/餐",
    priceScopeNote: "仅为餐标参考，不含酒水、服务费、场租或特殊布置 [MOCK]",
    seasonalityRule: "节庆、周末晚宴和热门餐厅档期需重新核价 [MOCK]",
    dateConflictSensitivity: "medium",
    minimumOrderRequirement: "通常需确认最低桌数或最低消费 [MOCK]",
    leadTimeRequirement: "建议提前 14-45 天确认菜单和人数 [MOCK]",
    requiresQuoteConfirmation: true,
    strategicCooperationLevel: "preferred",
    agreementStatus: "mock",
    customerVisibleSummary: "可按预算选择餐标，菜单、酒水和最低消费需本次确认 [MOCK]",
    internalNegotiationNote: "内部备注：可按客户预算争取免开瓶费或基础茶水 [MOCK]",
    internalRiskNote: "内部风险：白酒、特殊菜品和清真要求需提前确认 [MOCK]",
    contentStatus: "mock",
    lastVerifiedAt: "2026-07-04",
  },
  {
    id: "res_materials_av_mock",
    resourceType: "materials",
    resourceName: "会务物料与基础 AV 执行包 [MOCK]",
    supplierName: "KL Event Production Partner [MOCK]",
    city: "吉隆坡",
    district: "全城服务",
    serviceScope: ["主视觉背板", "导视易拉宝", "胸卡挂绳", "基础 AV/控屏"],
    suitableScenarios: ["培训", "经销商大会", "发布会"],
    capacityOrSpec: "100-300 人基础物料与 AV 配置 [MOCK]",
    referencePriceMin: 25000,
    referencePriceMax: 90000,
    currency: "MYR",
    pricingUnit: "项目包",
    priceScopeNote: "参考范围受设计复杂度、制作周期、LED/灯光规格影响 [MOCK]",
    seasonalityRule: "加急制作、周末搭建、夜间撤场可能产生附加费 [MOCK]",
    dateConflictSensitivity: "high",
    minimumOrderRequirement: "低于最低制作量时单价可能上浮 [MOCK]",
    leadTimeRequirement: "建议提前 21-45 天锁定设计与制作 [MOCK]",
    requiresQuoteConfirmation: true,
    strategicCooperationLevel: "candidate",
    agreementStatus: "mock",
    customerVisibleSummary: "覆盖基础会务物料和 AV 支持，最终规格需按方案确认 [MOCK]",
    internalNegotiationNote: "内部备注：可拆分物料和 AV 两家比价 [MOCK]",
    internalRiskNote: "内部风险：客户设计稿晚交会影响成本和交付 [MOCK]",
    contentStatus: "mock",
    lastVerifiedAt: "2026-07-04",
  },
];
