import type { InquiryQuoteRequest } from "@/lib/resources/types";

export const mockQuoteRequests: InquiryQuoteRequest[] = [
  {
    id: "qr_waiting_venue_mock",
    inquiryId: "inq_20260704_001_mock",
    customerName: "李女士 [MOCK]",
    companyName: "示例科技有限公司 [MOCK]",
    resourceMasterId: "res_venue_klcc_mock",
    quoteRequestType: "venue_availability",
    eventType: "经销商大会 [MOCK]",
    eventDateStart: "2026-09-18",
    eventDateEnd: "2026-09-19",
    attendeeCount: 120,
    customerBudgetRange: "￥80-100 万 [MOCK]",
    requestedServices: ["主会场", "茶歇", "晚宴动线"],
    requestedRoomNights: 0,
    availabilityStatus: "waiting_supplier",
    currency: "MYR",
    seasonalityNote: "9 月为企业活动较集中时段，需等待场地方确认 [MOCK]",
    conflictNote: "内部备注：同周可能有展会占用，需优先确认可替代厅型 [MOCK]",
    supplierResponseSummary: "已发出询价，等待供应商回复 [MOCK]",
    paymentTermSummary: "待供应商确认 [MOCK]",
    cancellationTermSummary: "待供应商确认 [MOCK]",
    customerVisibleQuoteSummary: "已提交场地方询价，待确认档期和本次价格 [MOCK]",
    operatorFollowupNote: "24 小时未回复则电话跟进，并同步询备用场地 [MOCK]",
    quoteStatus: "waiting_supplier",
  },
  {
    id: "qr_quoted_banquet_mock",
    inquiryId: "inq_20260704_001_mock",
    customerName: "李女士 [MOCK]",
    companyName: "示例科技有限公司 [MOCK]",
    resourceMasterId: "res_banquet_chinese_mock",
    quoteRequestType: "banquet_menu",
    eventType: "经销商大会 [MOCK]",
    eventDateStart: "2026-09-18",
    eventDateEnd: "2026-09-18",
    attendeeCount: 120,
    customerBudgetRange: "￥80-100 万 [MOCK]",
    requestedServices: ["中式围餐", "基础茶水", "可选酒水"],
    requestedBanquetLevel: "标准商务餐标 [MOCK]",
    availabilityStatus: "available",
    quotedPriceMin: 260,
    quotedPriceMax: 360,
    currency: "MYR",
    seasonalityNote: "当前日期可按平日餐标核算，最终桌数会影响总价 [MOCK]",
    conflictNote: "内部备注：同晚仅剩中厅，需尽快锁位 [MOCK]",
    supplierResponseSummary: "供应商口头确认可接待 12 桌，需菜单确认后出正式单 [MOCK]",
    paymentTermSummary: "预计需 30% 订金锁位，余款活动前结清 [MOCK]",
    cancellationTermSummary: "取消条款需随正式合同确认 [MOCK]",
    customerVisibleQuoteSummary: "晚宴有初步参考报价，菜单、桌数和合同条款需进一步确认 [MOCK]",
    operatorFollowupNote: "建议向客户确认是否含酒水、清真要求和主桌规格 [MOCK]",
    quoteStatus: "quoted",
    quotedBy: "Ops A [MOCK]",
    quotedAt: "2026-07-04T10:30:00+08:00",
    expiresAt: "2026-07-11T18:00:00+08:00",
  },
  {
    id: "qr_limited_materials_mock",
    inquiryId: "inq_20260704_002_mock",
    customerName: "王先生 [MOCK]",
    companyName: "出海制造集团 [MOCK]",
    resourceMasterId: "res_materials_av_mock",
    quoteRequestType: "materials_production",
    eventType: "新品发布会 [MOCK]",
    eventDateStart: "2026-08-08",
    eventDateEnd: "2026-08-08",
    attendeeCount: 220,
    customerBudgetRange: "￥60-70 万 [MOCK]",
    requestedServices: ["主视觉背板", "指示牌", "胸卡", "LED 控屏"],
    requestedMaterialsScope: "完整视觉物料 + 基础 AV [MOCK]",
    requestedTransportScope: "物料运输与现场撤场 [MOCK]",
    availabilityStatus: "limited",
    quotedPriceMin: 68000,
    quotedPriceMax: 98000,
    currency: "MYR",
    seasonalityNote: "提前期偏短，物料加急和夜间搭建可能上浮 [MOCK]",
    conflictNote: "内部备注：供应商同周已有大型活动，LED 规格可能受限 [MOCK]",
    supplierResponseSummary: "供应商可接基础物料，LED 与舞台需降规格或找备用供应商 [MOCK]",
    paymentTermSummary: "预计需 50% 制作预付款 [MOCK]",
    cancellationTermSummary: "物料下单后取消可能产生制作成本 [MOCK]",
    customerVisibleQuoteSummary: "物料与 AV 可做基础版本，高配规格和加急费用需顾问确认 [MOCK]",
    operatorFollowupNote: "优先确认客户是否接受降低 LED 规格，必要时拆分 AV 供应商 [MOCK]",
    quoteStatus: "limited",
    quotedBy: "Ops B [MOCK]",
    quotedAt: "2026-07-04T11:15:00+08:00",
    expiresAt: "2026-07-08T18:00:00+08:00",
  },
];
